function setDate() {
    const now = new Date();
    const secondHand = document.querySelector(".second-hand");
    const seconds = now.getSeconds();
    const secondsDegrees = (seconds / 60) * 360 + 90;

    const minuteHand = document.querySelector(".minute-hand");
    const minutes = now.getMinutes();
    const minutesDegrees = (minutes / 60) * 360;

    const hourHand = document.querySelector(".hour-hand");
    const hours = now.getHours();
    const hoursDegrees = (hours / 60) * 360;

    secondHand.style.transform = `rotate(${secondsDegrees}deg)`;
    minuteHand.style.transform = `rotate(${minutesDegrees}deg)`;
    hourHand.style.transform = `rotate(${hoursDegrees}deg)`;
}

setInterval(setDate, 1000);

function displayWords() {
    console.log("display words ran");
    let words = document.querySelector(".words");
    let randomIndex = Math.floor(Math.random() * array.length);
    let randomWord = array[randomIndex];
    console.log(randomWord);
    // const now = new Date();
    // second = now.getSeconds();
    words.innerHTML = `${randomWord}`;
    // $(".words").fadeToggle(2500);
}

// function removeWords() {
//     let words = document.querySelector(".words");
//     $(".words").fadeOut();
// }

function displayClock() {
    let clock = document.querySelector("body");
    clock.style.display = "block";
}

array = [
    "absolutely",
    "accepted",
    "acclaimed",
    "accomplish",
    "accomplishment",
    "achievement",
    "action",
    "active",
    "admire",
    "adorable",
    "adventure",
    "affirmative",
    "affluent",
    "agree",
    "agreeable",
    "amazing",
    "angelic",
    "appealing",
    "approve",
    "aptitude",
    "attractive",
    "awesome",
    "beaming",
    "beautiful",
    "believe",
    "beneficial",
    "bliss",
    "bountiful",
    "bounty",
    "brave",
    "bravo",
    "brilliant",
    "bubbly",
    "calm",
    "celebrated",
    "certain",
    "champ",
    "champion",
    "charming",
    "cheery",
    "choice",
    "classic",
    "classical",
    "clean",
    "commend",
    "composed",
    "congratulation",
    "constant",
    "cool",
    "courageous",
    "creative",
    "cute",
    "dazzling",
    "delight",
    "delightful",
    "distinguished",
    "divine",
    "earnest",
    "easy",
    "ecstatic",
    "effective",
    "effervescent",
    "efficient",
    "effortless",
    "electrifying",
    "elegant",
    "enchanting",
    "encouraging",
    "endorsed",
    "energetic",
    "energized",
    "engaging",
    "enthusiastic",
    "essential",
    "esteemed",
    "ethical",
    "excellent",
    "exciting",
    "exquisite",
    "fabulous",
    "fair",
    "familiar",
    "famous",
    "fantastic",
    "favorable",
    "fetching",
    "fine",
    "fitting",
    "flourishing",
    "fortunate",
    "free",
    "fresh",
    "friendly",
    "fun",
    "funny",
    "generous",
    "genius",
    "genuine",
    "giving",
    "glamorous",
    "glowing",
    "good",
    "gorgeous",
    "graceful",
    "great",
    "green",
    "grin",
    "growing",
    "handsome",
    "happy",
    "harmonious",
    "healing",
    "healthy",
    "hearty",
    "heavenly",
    "honest",
    "honorable",
    "honored",
    "hug",
    "idea",
    "ideal",
    "imaginative",
    "imagine",
    "impressive",
    "independent",
    "innovate",
    "innovative",
    "instant",
    "instantaneous",
    "instinctive",
    "intellectual",
    "intelligent",
    "intuitive",
    "inventive",
    "jovial",
    "joy",
    "jubilant",
    "keen",
    "kind",
    "knowing",
    "knowledgeable",
    "laugh",
    "learned",
    "legendary",
    "light",
    "lively",
    "lovely",
    "lucid",
    "lucky",
    "luminous",
    "marvelous",
    "masterful",
    "meaningful",
    "merit",
    "meritorious",
    "miraculous",
    "motivating",
    "moving",
    "natural",
    "nice",
    "novel",
    "now",
    "nurturing",
    "nutritious",
    "okay",
    "open",
    "optimistic",
    "paradise",
    "perfect",
    "phenomenal",
    "pleasant",
    "pleasurable",
    "plentiful",
    "poised",
    "polished",
    "popular",
    "positive",
    "powerful",
    "prepared",
    "pretty",
    "principled",
    "productive",
    "progress",
    "prominent",
    "protected",
    "proud",
    "quality",
    "quick",
    "quiet",
    "ready",
    "reassuring",
    "refined",
    "refreshing",
    "rejoice",
    "reliable",
    "remarkable",
    "resounding",
    "respected",
    "restored",
    "reward",
    "rewarding",
    "right",
    "robust",
    "safe",
    "satisfactory",
    "secure",
    "seemly",
    "simple",
    "skilled",
    "skillful",
    "smile",
    "soulful",
    "sparkling",
    "special",
    "spirited",
    "spiritual",
    "stirring",
    "stunning",
    "stupendous",
    "success",
    "successful",
    "sunny",
    "super",
    "superb",
    "supporting",
    "surprising",
    "terrific",
    "thorough",
    "thrilling",
    "thriving",
    "tops",
    "tranquil",
    "transformative",
    "transforming",
    "trusting",
    "truthful",
    "unreal",
    "unwavering",
    "up",
    "upbeat",
    "upright",
    "upstanding",
    "valued",
    "vibrant",
    "victorious",
    "victory",
    "vigorous",
    "virtuous",
    "vital",
    "vivacious",
    "wealthy",
    "welcome",
    "well",
    "whole",
    "wholesome",
    "willing",
    "wonderful",
    "wondrous",
    "worthy",
    "wow",
    "yes",
    "yummy",
    "zeal",
    "zealous",
];

setInterval(() => {
    displayWords();
}, 1000);

// setTimeout(() => {
//     removeWords();
// }, 10000);

setTimeout(() => {
    displayClock();
}, 1000);